services:
  doiboard:
    image: registry.upc.edu/sddstic-sbpa/doiboard/backend:latest
    container_name: doiboardbackend
    #ports:
    #  - "8004:8004" # No es necesario porque los contenedores se comunican por la red interna de Docker
    env_file:
      - .envs/.prod
    user: root
    networks:
      - global_nginx_network  # Conectado a la misma red del frontend y Nginx

networks:
  global_nginx_network:
    external: true  # Usa la red ya creada


